### 
## Connect-4 Makefile skeleton 
## INFO0030: Projet 4
### 

#---------
## Rules
#---------

all: puissance4

#---------------
# puissance4 
#--------------
puissance4:
	make -C source
#---------------
# clean
#--------------
clean:
	make -C source clean
#---------------
# Documentation
#--------------
doc:
	make -C source doc
